resources:
  limits:
    memory: "64Mi"
  requests:
    cpu: "10m"
    memory: "64Mi"

pdb:
  create: true
  minAvailable: 0

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: "In"
                values:
                  - "sealed-secrets"
          topologyKey: "kubernetes.io/hostname"

metrics:
  serviceMonitor:
    enabled: true
