---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: garage-cluster-garage-admin-credentials
  namespace: garage-operator
spec:
  encryptedData:
    admin-token: AgDDMpBlWrVcqh9cyVehXjIfGLs3XLqJn+yQOOlc1jaPCuy77vWkOU1W59dlhrdAb/xo1jPiwbfM9TsShUGAmJmBCPT7y1b4zE3g43aBFt50n7hGrmmQX5eSVNBrZg3rAtHog7q4B6lW5a1nBttJcOmvWPW1X/2MNTzswA8CFVXTvXFjcu6ItW/LCOXSGU+U5F0R6gDmG0QxfP9Y3Xp1dqbBH/0+DeWNDe1p7MAdqrvijI4CsfWPnNIyjSQ5wnTefUWRW7hmgRSbS0YnJv4TmilBDbOXmwP0zQk+3svMvpidfwCOHc1LrEXSKxJWHM72+5wTdookWpxVFVz3bYbQ1AGkxDWNjr2MvcRmMYqnaUuOiOFkRN8xxfN/tij+yhD2xtb9Dge/0xYpCzb/efldYJvFYtKCeUgOygh1qStS6Pww/KCSfZRTQSL+0DqNcAZBHgMJVHNdXR8y54vyr2iVDuHedWtic+HvyVkbiTmEor2QsfQ2yMlzDEWLeK0yHZlC3UpVJdQEIm6WzqFHJ12DMmzuu3DtisFfrVlp5G8tPzJ0F69Ba494i8kGFKIAf5uO1Cugznh2emUw2eKFp0kI2Xz9bVdAx3Maqt9IYTVTdWAU5GNPwcXHLyecZRhaM2iSwc6vtSLsLNwB7qwLduJLfQbOMR1r/slQS2jMlBGb90EWB+TWt/dkFkeKrpwXBrjUbeiju6sXPUaKNQkf7JP8fmn0WeQdxw==
  template:
    metadata:
      name: garage-cluster-garage-admin-credentials
      namespace: garage-operator
