expose:
  ingress:
    hosts:
      core: "harbor.nailforge.dev"
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "dns01-cloudflare-cluster-issuer-prod"
persistence:
  persistentVolumeClaim:
    registry:
      storageClass: "openebs-hostpath"
    jobservice:
      jobLog:
        storageClass: "openebs-hostpath"
    database:
      storageClass: "openebs-hostpath"
    redis:
      storageClass: "openebs-hostpath"
    trivy:
      storageClass: "openebs-hostpath"