---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: thanos-objectstore-config
  namespace: monitoring
spec:
  encryptedData:
    objstore.yml: AgBAn0eaRfP1Oe2F6sR0QXe9z0idMUm+qUPc82dhBdHZa5E573Mk7iBfsrzswAhttyDmH+c3GWjr1u+6GDeKWlNSxWi1mTt16m20cfwqa7+nBxIXxErjm13LyA6JYEh7zS4KtTlZiB/0OIK1FmmnusOXcBU5efW8uUlDUu0g8XumbBqGEmfRLHF83H68bGIA3NuCjEYiEhfMwXyxd26g0AUMvuQ1HsSurui16uFnJV5/4NCSt1N++Z1Dt4PxcO8+ZKmAKrMJqZ4QtGKoIb0IVYpitUkM7YrRr0LmGLM+MYv0L0mlLD5N/cB5XN5mxgc6oEcWM0obtmg3eA0OsdoopoHIJAPE3Gs5wMyvcTZN4o7p+4W9Rp3q/C8l2bogUQi7Kt+D1HVXYa7YTdWzpqzwekrV9IkcQEZD7XnZr40UAF8C3fQkfWR//N9dSbwrnamQMX4Q0ya9xiKBofqY0qZBJ3Ssv945T4aB2weG3SEBuu/HciOLNEna43IQv8EcAjhNa0rBVb37yepN0oW8GQeWAgIN1Uj4WaBX03KNPfuWORfxJemXqtQGfGX7kXUcJNeJX2ApqblIA6X1dCf+p9Fn89CkgWfjYxx19eRC2HZ5U6MzftBYRiIULyZfaEjzgNpTQknpmlQ7y1QUKfoEoDpNIxkW+znAopH0K1IzV8VfZBTCFZo+LJH/N2LeQ/oH0omNUT54PakWBHPb2FrrVz3PB5hM+PHVsUm64K8LBVYsogfRuyo4sHoCTWlDg8NtmMrrjev9YMdFSVJFRq0rAvPd7VutmWWiliyRcGjwAbSczVKbPdb9XEornx2HdtSQ+nNEgVUCSiBWHPcjdjaZRc3AxvqS/EqLYIoLkk0WVV1heW3M3jYWqjam62LafGxeOuzCVmAvVSbpqUk2arfwrvg4vdOXmLgM0A==
  template:
    metadata:
      creationTimestamp: null
      name: thanos-objectstore-config
      namespace: monitoring
    type: Opaque
