apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "cloudnative-pg"
  namespace: "argocd"
spec:
  project: "default"
  sources:
    - repoURL: "https://github.com/erNail/talos-k8s-iac"
      targetRevision: "feat/add-default-tech-stack"
      path: "k8s/cloudnative-pg"
      ref: "values"
    - repoURL: "https://cloudnative-pg.github.io/charts"
      chart: "cloudnative-pg"
      targetRevision: "0.23.2"
      helm:
        releaseName: "cloudnative-pg"
        valueFiles:
          - "$values/k8s/cloudnative-pg/values-cloudnative-pg.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "cnpg-system"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "CreateNamespace=true"
      - "ServerSideApply=true"