apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "thanos"
  namespace: "argocd"
spec:
  project: "default"
  sources:
    - repoURL: "https://github.com/erNail/talos-k8s-iac"
      targetRevision: "main"
      path: "k8s/monitoring/thanos"
      ref: "values"
    - repoURL: "registry-1.docker.io/bitnamicharts"
      chart: "thanos"
      targetRevision: "15.9.2"
      helm:
        releaseName: "thanos"
        valueFiles:
          - "$values/k8s/monitoring/thanos/values-thanos.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "monitoring"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "CreateNamespace=true"