repositories:
  - name: "bitnamicharts"
    url: "registry-1.docker.io/bitnamicharts"
    oci: true

releases:
  - name: "thanos"
    namespace: "monitoring"
    chart: "bitnamicharts/thanos"
    version: "15.9.2"
    missingFileHandler: "Error"
    values:
      - "./values-custom.yaml"
