global:
  defaultStorageClass: "synology-iscsi-delete"
existingObjstoreSecret: "thanos-objectstore-config"
query:
  replicaCount: 1
  dnsDiscovery:
    sidecarsService: "kube-prometheus-stack-thanos-discovery"
    sidecarsNamespace: "monitoring"
bucketweb:
  replicaCount: 1
  enabled: true
compactor:
  enabled: true
  retentionResolutionRaw: "7d"
  retentionResolution5m: "30d"
  retentionResolution1h: "90d"
storegateway:
  replicaCount: 1
  enabled: true
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
queryFrontend:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hostname: thanos.nailforge.dev
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "dns01-cloudflare-cluster-issuer-prod"
    tls: true
