apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "vertical-pod-autoscaler"
  namespace: "argocd"
spec:
  project: "default"
  sources:
    - repoURL: "https://github.com/erNail/talos-k8s-iac"
      targetRevision: "main"
      path: "k8s/vertical-pod-autoscaler"
      ref: "values"
    - repoURL: "https://charts.fairwinds.com/stable"
      chart: "vpa"
      targetRevision: "4.7.2"
      helm:
        releaseName: "vpa"
        valueFiles:
          - "$values/k8s/vertical-pod-autoscaler/values-vertical-pod-autoscaler.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "vpa"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "CreateNamespace=true"
