apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "hedgedoc"
  namespace: "argocd"
spec:
  project: "default"
  sources:
    - repoURL: "https://github.com/erNail/talos-k8s-iac"
      targetRevision: "main"
      path: "hedgedoc-chart/charts/hedgedoc"
    - repoURL: "https://github.com/erNail/talos-k8s-iac"
      targetRevision: "main"
      path: "k8s/hedgedoc"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "hedgedoc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "CreateNamespace=true"
