---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hedgedoc-db-credentials
  namespace: hedgedoc
spec:
  encryptedData:
    password: AgBksJad6M1XyL0O/I+O4umuBLQOfwbc1nWJG681KcFWPEK4rY1mHd3GvqcQWHPe1fDGMBRadVv+vWC6fpI8Onu92WL1oAVuUY6t2xef/41RQcE310SGh2r0f4OFo+Af8VHwJ99AkW+z9BP1biHAHWJCqZMtgpMYzhIvCHRPmoG+7lMyQ7Wbpea9ymDYj2Kq91bbSwlnQZnHmb2DpRS2VQq4vNImbI82ocWNiGKJ7bryM8p1j6XD6SdLLimyrgZnqMXxVP3E+FoHocTKfdaq6gnQhSvH1l4HQHtm6nNC2ypLbG8eDU6v+oIqcePfeR9FU3FTqFWWOKAW2t/w7LWDU/b4FDvfsg0O8o0/vPYIHms3y0YSETj445FPLrQdEiLHwnRbyQoWTFYgNlooM4KJaq79VpkT73WGdWT03roMtDDVHIJ0deqMFOybFmTaF0LzHcZs+/arv2IiWKZcTSx9U/64VXJvmx6QUBHsr8Ga3PrhSAkGrdVLWF2URATIGJFOw7nOdvzpm0aY6qW9g5uYYMSga63S/DRl+KSt74E+QrHHj3uTYPRLIVQXHdsXGIABRocJ+6eUPHE0VLHKlw5fMwG7XRZt4bU6ElFFvyJ7uPYoIVWofo6BvJEcPlgg0JBLpON40daYNQw2BkDSZaaQFA2ZZZTa2EhV6N51L34zN42sf6djcmGLbY9PxUPtgtmXH6W/8uEFHjT++58KHxKqzzciFvu7yA==
    username: AgCLtfgGJ4e8FgS0N+lMlQmVRXFKhKjk8yKXbyYtAZ1k+9LujpJl64AEv97EC9nuw1E/RS+tqJO29SNeKR+WPmI4FEJxR9uVK9K8EKX0alr4D2uPjVmNkSbMi9YKEA3+L8Nb6mDaT2T0zWg1iBEOuRvqVDV7HVaoeUZQGxS86dIuslz2jtoPnJ3f38BMEVQElHED9weid76IbQt/gwjJtNa0W0HAX6sbXUVIgFftC+ROCbGMpWXVDnuwM5tqfvxwz6RFjY6UT6KRhxxYzEM6ZUKFIa0sIuB8DdNB1BuDxizzrkop3oeocT3vLZgnymxXpc4kSg2AcPQBv7///pClREj7byBoNhq1cPYW4rd675QyDBTtS44IvAQieWGpTlTrhm8zO/pesfXkSOvqRwGHYYrDahlPn1bfMeob6Z213kyDsA35K25ZB1LxoEaxsqZhWRyvaa0tIM3w6joLNpx9zlPZHJY6Pq7h+NXU9kPq9tyUnSTa7hvkrOiQEZpWbUIXTf7su8TA/AsoDCo6u0skUoKkuTB8oq6wj9+ksQ6y6uq9m8pwqwr9vvSmSZJasOXkysrZnKTfCL42ZpCisX28M8GFs+0N6g04JxASK2QupwJX5oAtyjLyYgteA8GPllYWUpi4xWHOOgs0ndpGQSVqaIj4OyUaFXENz+eLqKIJnVlYjml/8EzBeMYpFUkA9imaQyY+neFyShi6Uw==
  template:
    metadata:
      creationTimestamp: null
      name: hedgedoc-db-credentials
      namespace: hedgedoc
    type: Opaque
