---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-issuer-dns01-cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAnV3Wn0DNGWmg1o7idZLs+lDYImOnZvd30WsWUv1pITc2b1XpxSt5w9NUW5OQFTdbTMUP8MulIUa8mVFxXtAq21IZSdUv3ltV7jqjFbdj15sY5BsV353kUrS0FCOQ1H+nb07RojM+Y0RUC0DXoPFWeRsp4R/aAodD1H78yO2OLoUlGXwvK53+YW5JohvasCIo98tWJvO5+zA4IvyS+mNECgQeIWNoR5apU/RZxt55d1lygE4rMyKEQZmy4QLVRjs+iDkHG8U6fCHewkSIdEWBNUFrEuZxthK0+KE1wBtQEowq6Kn5cSmQcMQz+3m191LkozNG/FMohO1cfgBrAbJIiaudI5l9BeMiaw9ZHQpflYe8kCdemMf1ZMtWlm7Ye/wYvkXllPmpx3cA079UMKfaSHKHrntBc4d5CsZSSvcY3/qkfrLItGN+2/iQatul1lHk8SC/vvqEgWvUnl7JptV+bJKrRMRPN0UvVd97p7xS+NFPtxGNxmJ99+3ZMfHyzvh0Fr4vE3itfuMddIptfJ6uTvGnmP5b3Ql+83TLHfi0F9M5cIQiZnqweQzUlSsKozNs8GqyEL579Jqm4FfwSCjoBr1tcSB22/53zMVsXqUwVFf5BlcrzVJysBktHdcuMcn2PQn7KA0jRm//IxBT7wnrEleqNqWa/dZm1ywEM7JDCGcB8uokZoMdTEvvVW0BLvEE+qMCnpxsGY3fseotk7MRXp/cYSiBC7R3xcfuNDF3cEvhUpiY8piOx
  template:
    metadata:
      creationTimestamp: null
      name: cert-issuer-dns01-cloudflare-api-token
      namespace: cert-manager
    type: Opaque
