apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "metallb-config"
spec:
  project: "k8s-default-tech-stack"
  sources:
    - repoURL: "https://github.com/erNail/talos-k8s-iac"
      targetRevision: "main"
      path: "manifests/metallb-config/"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "metallb-system"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "CreateNamespace=true"