apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "argo-cd"
spec:
  project: "k8s-default-tech-stack"
  sources:
    - repoURL: "https://github.com/erNail/talos-k8s-iac"
      targetRevision: "main"
      ref: "values"
    - repoURL: "https://argoproj.github.io/argo-helm"
      chart: "argo-cd"
      targetRevision: "7.7.11"
      helm:
        releaseName: "argo-cd"
        valueFiles:
          - "$values/charts/argo-cd/values-custom.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "argocd"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "CreateNamespace=true"