---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki-objectstore-credentials
  namespace: loki
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgBQ3dbrt9C2/4K1vQO5XLZdhkGzlib2pB2Jm55eqwpnsxjBl4apAUqyngW1KBnyvznq8vD+wsjk4rBJfvcEi5oeEvXJEnXzgEp2/AFAeBhtS+TLw326mjPOCPD0k4ILClZAzKW3zArScW2ZR61n3YUGpmpwGZKaxfuV5cLYt1rr3A0fBoRGrh8W1l+ibKz3JHBEMYxRnOJ7lgDZjZ8MHyISU9uXNoIoQQpXUtayirWZ7MrZhA0MhwAyPYDX4NsIexHjIckGAlCxkvejArKFzvU+4reMgRWMl41MaEDiBxrWt3/ES/7tHydmIw+/+xaMnPWMJn6j2TawrW7GPe8sLOLMBjtNrs5yPI2NLtn8Z+6CEJqEJWEmfWd7ZQPK9G0SxUO3TfJo2YuEwykARWTyXa9S+hVr14mCkIYJdLoSycPSyuwYyuX5EAuzDE3u+MDtX4c/cXReA4EIFgjeh1svTEeDoZVD+GQX5Vh6kV2xpEHestH+9azgcDo5LWlwQtNqyF1n4cogMZE3OwP71ICRtM5An2wLkmMbnWEsedLOGZ+Hqrh2McaqgjPPGoDH0MY9Za8tfnlbig9G76QJqPUwNYikwzVbBsiQ+QpUfCv5gQxMJm0LSzrgIf4AhdnSsoJW9GghCVFDnz2RrkWJGHKWCxBkWIxXTmsHVcW6yZzXVGzjqByjwn7yoD7M0yqnGBNzhqtbXHy8jvb8oOg=
    MINIO_SECRET_KEY: AgB1NXf/iVAigf0bRKigQOTBAlEtbMk9ksXoDT2+ULvRC3ykCC91ARz9FR4/qofCuAhR+qyrIoiTTOwGw1jwsvnsQg0S95i6NxmB6MDP4l65TNvQ33GRhllY/HpNcaWcz/cUBI1WH2lOBt3Oy4wj86MgEyfZcVCIIYW3Asz85VFv2pWo0wbrXvNYkPQoEZDnivvMyFVCKBeEaxUtxBM611SFdHYeY/dQqiSfB+/jV8vWvUUOehX7o8/ZIBFP9hTKazSx48RsVwmKVvI7XiGWRokS0GY6q3Gw/codC0C79uWKNwt/lS0zIVRxxyUNYNSw6D4xNG+tQpgwZM3xGh6XaJHVKJnqPxV0aCaql6HQVLKLhzCnbODyT9wYmd18iespnOn2WNQx8GAuvlN0LnLExdstey3BcJups3CdlJ0HzXPq4M66lx9LJuygfJlabeEAvB2cTSPfLospqElGf6Sa6EHyJ/TxaSpKMDo5CBnco14ZuLfe+K5d7CTxx5BMU0kYYE/W+M1uZ8+HPwcjzP5hyOuTK/xR3S885HQH7U0WmU+ZI3WxmY+QskSgwSg5xW/XwOrVg1vI9SVniWJbtzryeVd2yoo/kVES+eKH38ycmDJ1eHNJTr4+JKl2elWWg53o5d2kAJnxndG9H2o+B0CRez+/71ge9WEVYKlV75Tz14PNVviuRaC7r3XY45eknEF5trZ97scCSsUAFZ7DNEAaxwEprRCVJA==
  template:
    metadata:
      creationTimestamp: null
      name: loki-objectstore-credentials
      namespace: loki
    type: Opaque
