---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki-minio-root-user
  namespace: loki
spec:
  encryptedData:
    root-password: AgA/Z05/7A8fhqM7zLWM2aOX22eEwbXo4nH913kq5zkbmVNzrGxqSzIIjRqd8pGOuIoGg+3wsHskgeLLGKLR2HLK5mo9mK68+wPPyEDIdcDrxkMvIs1D7zDm7KdD6PqmzKRW15VGNglteqYNjRk6HYGwUS4w4TBinJnV58pw808cV1TdvViDTYFyY48UEj3CHDqfoR7cojzDPEY6ZV09cT2mqmc3FKQRKR74jLzokuS2KhNIExf6xRjkJ6idLfLPIv1kPvCMbL+HmEQupJgm8MAlo21VTVw9/mVzwt/aKsXNNkzOAYqm0zWvnP2uJ0ir6ug/PnwUKKZjXhjfy5CnVbDxOlidInQIMG5bJGu/0vbYtx4zWZudhEzYkxfWo3aPT7NOYJxWr86pqKxqNVKaDklkWcXZz6eIx4XvzSYaK2Hkl+DsihQFQZX9DpkJtEM7is+2+gGZSQ9D8YoHRzRG0k+ho5vhp5ZokGS6QHoumhuHN3HaF4w7VK6nhATiAYAbCXMzC+OGorP3mQuX7n1U6fOtrn0EqV+gRvEm70QS9qkVsQBO6OA/9vhiOosrJ48k+/tf4WaHWe7P9V+SAmLfvysyTD/tbIoczWq2ppRwkDHFOgvbeLqCUFQJwdZDb+J6TTBgmbU4MU6Ogv5739E+c9kkZHAuVFxdLe8Wz4PuJn8kyNw450Z+NE4y+zZisqhpkaCudrrZClXm87s8phTgwUSi9eHEzw==
    root-user: AgALxGNAzJWePnrVEAOk2PqFpkiGYllgHTkqGR6C+mYC71UejivZVPb1SYD6tIiTLoLsMkasU67IG73NjpkjUudPII9/MBsqGxT3nY/B5zQsKZ4Ku5w40/xD7BJb62YLuuYIhX7EQbBQaVyuoXfmBv5eVBdsuwc01fZXeMac2ApzgpHkLCC6qTppt5NP/VbvIItWqtPvfIaz+iXFyukM4CBTR65Vdf0gfyDu95u3h0/Jg196ud2x4g3uW9ZKVwJvnAZcF19m1SKfOVeoh8ax6gkpEXanR55fIXZ/VjkIz4Jm36v7HR5V0CcwqnRG6PrAYdeH7sdnspi/TdUx0JGrl2qHWDQPGotY0lhz4NZima3rwvzSVXn5ZbcrdFcMsiz/SwKBTUoma6w0dJ9z8qpMMpDIxDtKfquVOv1s8ZgDeVVPEOSVi5Iihpj3YI6OS4KkyuumhlwBAyBr+pbbOgX7QPY0BdUMZIpTSY8YqVGU1gR9VY42cPOCUv32ozIUHtBPGeKMWKLxiZFK2RseDLFGSGvV6jzmN3QBj6mhvt/+skgnGP551mGEuRqQYK5VAX2R/Y16vtjX5h2+EWrzrNiyim1ji3lt0v5tq9g3Z7kDGo5eDbrplJcVB7BzmvOXLaZEy2bRLwbhyvO2x0msbHQxQ8gUEhrW4B5pIJ/CNZp7t6G69KyxDFyKGi50wluYqxt/CmsPbdcBq3rvSl8=
  template:
    metadata:
      creationTimestamp: null
      name: loki-minio-root-user
      namespace: loki
    type: Opaque
