apiVersion: "cert-manager.io/v1"
kind: "ClusterIssuer"
metadata:
  name: "dns01-cloudflare-cluster-issuer-prod"
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "nagel.eric.95@googlemail.com"
    privateKeySecretRef:
      name: "dns01-cloudflare-cluster-issuer-prod-private-key"
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: "cert-issuer-dns01-cloudflare-api-token"
              key: "api-token"

