---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: synology-csi-client-info
  namespace: synology-csi
spec:
  encryptedData:
    client-info.yml: AgCP+PDjZXGY+OK4gWbyQtS9/+iE5MQ4f/8pHNEgY4/wXWxLPtcKkvofAbFLdd6xXgEvHKzlhBfckNliCSnwJwgwBker8UPhN6IpV0MGkZKj6jOJF6tj7NM3UlBp9XWjV0VTiZ2AKZ0NuCwGFCtcEQBTmwgt3vNowsSvsjZWnOp5dqV99M1gDMjqiWZLRUoERbDUDurcSc4YE6uo0jb128hOj/VCZT/yI9GCDnVqQI+2dzJArxG3NrRxR0WYczQytjyCVvHvGCSRpH6fWghMTWNUNVyW1FdfTtXteUCmZzQh6Lzd7t9VTKiXST4oSzJzTvvdhckZt2FKrE7X+3GVB/Om+emFZxuSe79EupKDg2UNZxXiC9QZzcm31+iKjb8vqULxp0kkJ02BNGMLvMfym4hcW9WvJ4RdLNc/ADnHneWGYvnjQHEtHjff0VwAmhJOF8gFxp7toXIZRYQOLnWZsLf3m0vQA4P9GHGKFx9yEasrMm6ETuJeOvlyq89VZ4HpGsdIITRN5PsTNNwpmMbnCJ23D8UeWTyZhxCjYNh0WZYhFoi8SOO+5V10Sf3BjxM0edtMZhhQYEBY0Lcf5wBP1g/tHDb/qF78M4+0DwTg/vqoCOyacPAkUhF6ewhYh2xRV9KCJVhVAAx7vdgqdbySwWNHpXFJZpyyO71/2YuMUnbEOM3xjo4G7lf1qxWYnQLfQwux7ItQ6fOMwiCjb/WvGSvOLJbIo+ys5vbxUzb03W4Iaw4zsK9Q6yzMbN369uloFCOh0qLfJmtAoRf4XQgR+GEdXpjjHTJ0Hou5x7OtWUOhsPiWOlS1qUz1fdi07kAg3Li0CzxMzJLhR0FD/H0sdW7BBicGJ3+Vn/VgyGyX6KTmKtWCdg==
  template:
    metadata:
      creationTimestamp: null
      name: synology-csi-client-info
      namespace: synology-csi
    type: Opaque
