apiVersion: "storage.k8s.io/v1"
kind: "StorageClass"
metadata:
  name: "synology-iscsi-retain"
provisioner: "csi.san.synology.com"
parameters:
  fsType: 'ext4'
  dsm: '192.168.178.85'
  location: '/volume1'
reclaimPolicy: "Retain"
allowVolumeExpansion: true