apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "loki"
  namespace: "argocd"
spec:
  project: "default"
  sources:
    - repoURL: "https://github.com/erNail/talos-k8s-iac"
      targetRevision: "main"
      ref: "values"
    - repoURL: "https://grafana.github.io/helm-charts"
      chart: "loki"
      targetRevision: "6.24.0"
      helm:
        releaseName: "loki"
        valueFiles:
          - "$values/k8s/monitoring/loki/values-loki.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "monitoring"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "CreateNamespace=true"