global:
  domain: "argocd.nailforge.dev"

server:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    tls: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "dns01-cloudflare-cluster-issuer-prod"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
