---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: thanos-objectstore-config
  namespace: kube-prometheus-stack
spec:
  encryptedData:
    objstore.yml: AgBJmzvPT7Z7jowP3rcn6TZu0sEJ8x7q7CvfpJItxElUuX/gFGN/3SqtuugFHY6ttIn3+5T5QZ17q+iATxKNZuJoNqqAaRW8IcR78Ebwl9qMWz4WHgquAGE/mt+FNw7inJ1ABiTI31XLhd8VQx91kaJUF+nLGbsAVPDNUobRq6COEC5fAdqGknqWUO9Lb8NxzyUjL3MOoHWoKjMKWhMx1GIRVe820/gG3oPj5RlvjNmel+dy4TBC3xoww/RA7Arn88qApPuv92V+AKVnl9EH0VFCi8SY38rK4fttzo5iPUvj+Rwjjb/WPC/iVX1QhkFXEta3FtSZwc5Cd9zf4MOSZKWpzyDtfqh2fzjKXzbm0g6iixBBLFhvYjdDhXe9EdC4uGcb+HCF4hYNhNefTc9HFVl3RIoeHVvoK9MAt8AXU85FDNiLTpvp20J9XnGknCQP6yAp/UKaPSGyCAyEdz+QLATEfoIdsRGKox5TRHpywSSpGo/2asAU0eiWqlMW7//SlLsivCE40HUD+eY/hboPpvfrAFrD2y4dsxBz2dwcY/1rBRy5Hu3Ea2Qh7KkJH7UEXawIpVaAiHVRBMirG1iSopJ3Hcko96QpH3dTzw6JDIYmJyrIn2a81NSeEg7CRtCLB3G7QHOFJzNw+olPBD+kv0dADfwGLW4j+0HwbOQdRcmRW2J/GG6wB3DSKIorTDUje74f1udFxz4yXQEBcpDZSAl2QLBBqh3/ckdoZb+QfeOnrwF3+Lbpx+OzQYDZbiUEbkAH9lQuc5bGNXH3fkB5SNOfGvSQvrpUJjh8bS59v8K2961p39Vl0D55Izjz7Rtb2FwvszjZIxVK0t19lAL6JOgBpWFLORnhvgUPSjxfY8oOwMmA8zbXy+WExjwZRpcnVOc2rb01JCGSeg==
  template:
    metadata:
      creationTimestamp: null
      name: thanos-objectstore-config
      namespace: kube-prometheus-stack
    type: Opaque
