---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: synology-csi-client-info
  namespace: synology-csi
spec:
  encryptedData:
    client-info.yml: AgA+yKCSIEX/lVWy+8urRTc/amUM4tU8+gkE0QOj3u8KEfxkLJFmBmv0k8VZc5ywF6lw5rMRdbUNCzoUytSdsvZYIYolKpfFSMnOZbVsXqTXdRJpJBKtEDhopp/tH1p+1KMBklGlRyjTbojyri96lngw//gIhfwo5tW6KiKckafFXzSLIEORBLN8PfrxLx+VnJ/f4NmnA8+Rwf2IYK8Gzkpx+pkUs09CoLGCGiFIkueaTmzD+3yUuPveb/0luVisao7u9vEcFrLU5Z6/30gu0YC2elz1MKWV1Aq6NdYYW5PoXBEGmHke4RKM4fbfW68OD4OuoRjhnQt9ao3YkxQsGfkUq3hDY0OZYVuipu86B/vXHv0WgMCXnBlBgGLURxqVRV4YjcbldHPmZkHmurB5JmkyUdeeEW6koaKJN/MpjFcd0HWXF3BHMZO5qmG46tgiWjkR07UXfRoLRteTdAYNibVEb63qUVtxkwpII9ZPCOUTsn5Km0Qhfg4XDyXG+1o04H46ZaA5dX4rCRwL6u8Yc554RWCH3LQSCTf2KrP63HddRjbs8UrqR1cjpuHT/699sCu4CMHhQWtyVxftPipRBEKiC/SnZdiyR8EKkiccaEFCvgZ16jfG4dbjuOG/1Ea0I22xYb/Z3GSCtI4AW74Lo9F7EHq4N0bifwlZTUR8dmN2eIIOgbfgpecplev5w0QtSmKfQTsx9A/2MOSuliKGFWKUPh2vsW010PcojWRTmFv2qFRqWMMicRzjYKqSGfTQDEjmosXgOx3BvL7wfYpftuGZ6vEwk4gaAi0bkBR4iPSZJAGDPWgJR3VJRY9ki5vNsa1ICjmuBSBQJrBbBIDx+Ws0VBXv7GKQdbyjZG45xQ==
  template:
    metadata:
      creationTimestamp: null
      name: synology-csi-client-info
      namespace: synology-csi
    type: Opaque
