apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "nfs-subdir-retain"
provisioner: "cluster.local/nfs-subdir-external-provisioner"
parameters:
  onDelete: "retain"
reclaimPolicy: "Retain"
allowVolumeExpansion: true
