apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "nfs-subdir-delete"
provisioner: "cluster.local/nfs-subdir-external-provisioner"
parameters:
  onDelete: "delete"
reclaimPolicy: "Delete"
allowVolumeExpansion: true
