---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argo-cd-valkey-credentials
  namespace: argocd
spec:
  encryptedData:
    redis-password: AgBcIB3qTKTDyLxBdtjL4mjL6/jtqbzg4ZdmWS0tlgwRKUJaC9VMmNWXW2JM4Yod4WFyohQrEaXFQGKCX5FoHpzyRqGUiNjm5TDhe+w5oRRhCgsK2fk906o7U4P9wm2wGC5jc9yAQwJk5rCjCAvymBJbIJnI0yG/5kYlrgQM0Ru3wS0VWMz83tathg5J8hYgr3ZV1guXolYyn/8m8kmSj2KY7QkfK1xULBZ1m9HlvUCUD7wVV+C2IufE3lpRjivZdvH6xpi3YBBJoxHqH4EkOFpknln92sSJUNcRlRimCtcGza5rJ7IrSuCUDw88NXMz8W1xv949AZiOKjfMbI6mbP8TIggtCZ5NYwN0LB5II8TI11HkIP5vKWKZHpuHPCcJ4QaxQOlRnZuY+fzQmiKgoTvtt293/dtc2GdX4pG1gTgpK7zkfSW0Xgq2Dd3XPzNothVawRExbXYnMzPC8bwEab1gY/5QfIRCiYrd/SqHPz2W1Qfd80YZDCnAmSeQKNOOyVrU6U6DIzwSzxbKf05py8ayh9JM37jxOoCyWB2v4IU/PJkmNlmdu2T9+/E142tx7ANsmf2iuGmqTACpHnAGMmicbLYby8NUwimr22noETxIMDHt05Pg0Iwu0XC6xrq5wVIk32ks99WUEMo64uGhK+8tEzakh+mmQxJZPWvc7L55hpp18pX+KOXw/m4ID/NrcEywRxg=
  template:
    metadata:
      name: argo-cd-valkey-credentials
      namespace: argocd
