---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-cd-valkey-credentials
  namespace: argocd
spec:
  encryptedData:
    redis-password: AgBVAvSyiq5zwUg2yU0FmnVzG5IHbU7AUpu5ZdEns29v18GszbuqpwaCf8vzan8zVcTHZ02U4ZqvmP6b+dEzYfQGx2e2KTrtw+UKzwvpoJEGGZF/Fh6uaKHM3li88tz7K+o8ps1rqWCrIH1n6QxiFi8jIbhdY+Hux+Q6cjpfB2JMQP3gm/LKtmAQlopZqu18Ri+2vvKfgeLQgsrxcxRADojFOx0bELLjgYV8UrrebH4HEXeYWat/semNxR+F8JLqmX9ue52JLjf6lRWKTheil0YjkOIpmdBV5sStDH2wt9jj98UTlL0gQ53+QOGAgjms0KUNz4xTNXMidpvmk8CPP82Knw+os7T0iTiwPZReogRBxbud+AbEBs0tupLE1KjMrHO7zg7sVu66TfZB0ybNj4bnq0lywgSooxeAMkJqiMakKtceEy/dbl94Zl8DKgDRdA5bXiXWQ2/NSIt6vhqWjVrsTMcO1ZG/dbtjDf0u9iCi5mM1P5LobrNlk0xDLwEkp2SneQpqNAGiXMDWxGrWYl5BJCLucy+m4JitVAOkqyATIXcIbQgh5BI9FJD3yq39leO+Q1Kd6YvU/OFwLuoZ0+Lcx7PdUhOa71qcsRE+tzLMdD0tt3Gwomv6BXPLqy+KZc0ZcAdngwj3M4YZy/RmhgwBjm+WZJRNmRwBzfjlIfpUZS5We3KlMYHOwg/icWqTF4GqrJn8xd4Xi44lrVE+LzJBEvNzAg==
  template:
    metadata:
      creationTimestamp: null
      name: argo-cd-valkey-credentials
      namespace: argocd
    type: Opaque
