---
global:
  domain: "argocd.nailforge.dev"

controller:
  # replicas > 1 is in alpha
  replicas: 1
  resources:
    requests:
      cpu: "500m"
      memory: "1024Mi"
    limits:
      memory: "1024Mi"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  pdb:
    enabled: true
    minAvailable: 0

applicationSet:
  replicas: 2
  resources:
    requests:
      cpu: "10m"
      memory: "256Mi"
    limits:
      memory: "256Mi"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  pdb:
    enabled: true
    minAvailable: 1

dex:
  resources:
    requests:
      cpu: "10m"
      memory: "256Mi"
    limits:
      memory: "256Mi"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  pdb:
    enabled: true
    minAvailable: 0

notifications:
  resources:
    requests:
      cpu: "10m"
      memory: "128Mi"
    limits:
      memory: "128Mi"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  pdb:
    enabled: true
    minAvailable: 0

redis:
  enabled: false

repoServer:
  replicas: 2
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      memory: "256Mi"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  pdb:
    enabled: true
    minAvailable: 1

server:
  replicas: 2
  resources:
    requests:
      cpu: "10m"
      memory: "256Mi"
    limits:
      memory: "256Mi"
  ingress:
    enabled: true
    ingressClassName: "nginx"
    tls: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "dns01-cloudflare-cluster-issuer-prod"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  pdb:
    enabled: true
    minAvailable: 1

externalRedis:
  existingSecret: "argo-cd-valkey-credentials"
  host: "argo-cd-valkey"
  port: 6379

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
