---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-secret
  namespace: cloudflared
spec:
  encryptedData:
    cf-tunnel-token: AgB2MWayz0CQz+/2Wt5Pz8ww6TO1mnJEyg9oAYAwdMtt35VwyDFODi+Wyc8lbvO2OqX7GjMpS0X3vN+Ix/YQ3DB0ybiuOVvqzotJtrHyFotXceptTPQ2gV45IKCJMM48hNlgnRXbss3MjDBcjs0vL/snfUsq/vOMmVGG3fLjU/EZMRWD8Av2S47nsfc2NaTq2//TyR45eEVnfInndUuZq+PX9cLt3HR1Faq5GxxNRGBUkrqh7SFIxGu+EF4DR4LSFK+q9XT8oNNRQytWW39cl+5/drQO19GP8qo2gjMeIGfgw0OnG7ph8J078aTiE2QcMnZLOKaejuRXbkVWiS8HdcYLdlAHjkpd1JViL2rqjM4PwuzV7Ppi2+mQG1bTllHn3tG33JjxVihidTgpHAOoM9QKk7KtRfFr7nRv6+CxlF9A2YgSZTSOGs+OT52fA+hXuBG7lot8+xDYasMpXTAc+xJKv7MOxhrzMTzHWMDbqysBL9ilEfnMASF5bZO33fRV++pB0Jkp43jNksAQVYpUW/v6+58uXXBYcs5hg6CAXm1G0e39EEDUAQ8Tq9kfCZ2nxJDTQpxNWEEv//u+6eeu9So+AuhcLTd8HTiQSiyKJJD3N+mzFS+h21V6Jm3V62mJUDZKoLgyYtpdrll9qAB9hAbX6kGR1u9UHzkoWP/5G4yBkIonnE6kmkRU2xihhme6082fExvEGR/O5BcW3itmclTFGubEwSOlfETs0c0P4Js8jtgcNbgyDduWS6yx6eO3B/uRSGk0Tl8CA8VwTtSOStvQJ5I0MutBLcc7VQfI8GTyVa0nDQsVhWRI7af54VxbVmvOc1u1mzoJLEzlP8nMYMuV0tlclFNc1BEpXfQKDziyDTioJ8g9TgenJcKkKLNqWJb38YePQ3Tme9QFI6kL/ZrHc2q8LySOF7Gax6Eq46VCqcmHbSXkaOX5
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-secret
      namespace: cloudflared
    type: Opaque
