---
crds:
  migration:
    podResources:
      limits:
        memory: "128Mi"
      requests:
        cpu: "10m"
        memory: "128Mi"

admissionController:
  replicas: 2
  initContainer:
    resources:
      limits:
        memory: "128Mi"
      requests:
        cpu: "10m"
        memory: "128Mi"
  container:
    resources:
      limits:
        memory: "128Mi"
      requests:
        cpu: "10m"
        memory: "128Mi"

backgroundController:
  replicas: 2
  resources:
    limits:
      memory: "128Mi"
    requests:
      cpu: "10m"
      memory: "128Mi"

cleanupController:
  replicas: 2
  resources:
    limits:
      memory: "128Mi"
    requests:
      cpu: "10m"
      memory: "128Mi"

reportsController:
  replicas: 2
  resources:
    limits:
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"
