repositories:
  - name: "authentik"
    url: "https://charts.goauthentik.io/"

releases:
  - name: "authentik"
    namespace: "authentik"
    chart: "authentik/authentik"
    version: "2024.12.1"
    missingFileHandler: "Error"
    values:
      - "./values-custom.yaml"
