apiVersion: "argoproj.io/v1alpha1"
kind: "Application"
metadata:
  name: "ingress-nginx"
  namespace: "argocd"
spec:
  project: "default"
  sources:
    - repoURL: "https://github.com/erNail/talos-k8s-iac"
      targetRevision: "main"
      path: "k8s/networking/ingress-nginx"
      ref: "values"
    - repoURL: "https://kubernetes.github.io/ingress-nginx"
      chart: "ingress-nginx"
      targetRevision: "4.11.3"
      helm:
        releaseName: "ingress-nginx"
        valueFiles:
          - "$values/k8s/networking/ingress-nginx/values-ingress-nginx.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "ingress"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - "CreateNamespace=true"