repositories:
  - name: "harbor"
    url: "https://helm.goharbor.io"

releases:
  - name: "harbor"
    namespace: "harbor"
    chart: "harbor/harbor"
    version: "1.17.1"
    missingFileHandler: "Error"
    values:
      - "./values-harbor.yaml"
