---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-db-credentials
  namespace: harbor
spec:
  encryptedData:
    password: AgBjU8dgckI8ti7dGbimd9TrXiPJE2nrCFDiDy1PrDt70XCSvK8aHlqJC3Ra1xiquteZJk3f7AyqzPfHsbdHP6QpO9WlwPx9NEkMLC2rU64nQ9qwkz+tMB53Qfmqrb6o4i9idMFtpoT1Zf3xioQDaijBjFBal/2VEJ9btlIE0H6Yqym+pvjIjzvwlj1/zdKOGIfEM8huwJdVOps9xRGXHlz7hCkktUmwXWAbdBakQE1zK6YMej78Mq9BR5Zjw9SGlQB1w5aNvV8VOlvE79lRoTleSreXUs4zaIu0rNL5Xe8ZBPSQj8ClhYViLhwYLt9FDzoLKuvbXdZaDYc2xq0WhPAc8WK+a90/IMi0NB9nhIIRaAxsDAebanh8sgmBtjxfjQxRSWj//m4Vbju8suWIOcov4f+w+jMSPEfjkfwVuV3se/zriPXQnU6u20v/4yUmUUawUVpefq9uHmT2k1cw01ybe1u/YHGTj/iiStjRKoHYk60eFaQsy/XdUw4lsZWyo8ps7LXF6GHvuTyPuxCeLIlIGnjdaF1SbTIgPG+0whAaUAfJB4hQVpCY0L+7hGCGfyGNK1naYgdtmssow/sxsbxXTq8+oH8tNMvVIyZqRw1wRqFAhGK8tmMR3dHzBaW/m4Eid/oMpw+RawGdT2SeYfH7a56usnaRiUGnMYqeyT06PsWVMhXQRs0QZpjLLGxgpaQj59+CJeqaPpNqBXi2+ufnhu7plw==
    username: AgBiYyJIhg/zVK4CHTzBEQ/EQmMwqsgbnntih1S+dljuqWAPCbH1xmU7H6BsU8HQocBR62nm5eENqhrUZH+dJux0frVJ85wJMpJQydJL7xqrRyUEB3tsxtyGj+3Yt62nqzya3zuPnKV6omPQwRiYs+4ZI7yOIrSs+2/HOQv0Mhl4vzQl7JCT4EJLYllzpDRhaivaMBJIENSNd9minTlevUa/Aq6QeEv9iwJWekksjxJcnxSAzsHpMEeKBeVOa2ulxoaqVcYJpunm1cyn3Gzl3k6CuyeCB/0fT9kKLro7p8PgO7pXUuCCNDHqdOhlCBOSMtMHPzCwAp7q8qTHqFWDxERjUfzI3clFKto1mz1vYJ5PXFwrUd7Q8ksxfR78cgK3Yhe9vqEjHkiD9gSsRsBNuYvrU3ThmHf8/e742p/ImSGwwOs/s2palLvReBqllH7j46+gnb6c/nBk2heLibSA6tIrsAmgMWIiO8Gsgwn9v9w3YG5bMs10Hhm0Q2h6tIRGxGy5trk9uV0Zpunr5/ZSctA7tX+37uC7hUy3LGjj5wDcDn/83ZPe82WLdU8muMcA3W+UxgXq1ZeD+nVKrl3H8BwbXPEWAm+5NUjxXWbxQ0Kl2NGrYBY+ejtDbEaCGabG8+MtymT643qOVquLQEhLhJGBBX1x7mgdNR3A5hEOdW+jbSWsHJIp3vZNAbdEP+21HGTfzktsxg0=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-db-credentials
      namespace: harbor
    type: Opaque
