---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-valkey-cluster-credentials
  namespace: harbor
spec:
  encryptedData:
    redis-password: AgBLubFDiq79EVNfHnfnft5vU+OVA2h9i9rVqpZbo+1dDfEyb8UzrEvYJJ+VCbvub3Gn2yxnvGflyIny3K4vzdcORRffRUhK1Ngd+nJmpRD6W5CSXZm/prH25h7H8Ev5ueZ9GEMIl42AYMk5NSxlCfPyiZM9cfyHBq4K3aueAsulT3qKK3axzpxMX2dy/4AR0KzqRmjkRXIdqxaCm3qsNn2HM+TH+KiPKFvFla4SdIIv42NwrzVZbYUmsLAWRo+gXns4qCy6qjPPvQ65qcS566ngkvq1pKCAGBw7fSU1SdQd71r4LCVnI4K81OxAHkJzoPdK5mD6WYqwHOEBDbGBej16iuWUU2/wWGgwJUTQlGwv5AkWZlSGxVklGNJ0q4MRI3lBEicOAhMkF4cebEJgmAjmX3/73wr4PpguMwZWMnN5O+Dtn2LosKwye97iQGEUyrsjDcdToU0Ps8h+OsdwrG5x15YW2XTOfNSVk8MmNBWypmgJqbw6yLwDoPFn8bb1QmBdM2VweC+OLTjGh6GhaOo8sNlnFpjIpi5p48v7994TmfMbLdzApmPqRG7v+s7A9BaK9f1mdDHsb9fqmeZcyohh+eh7/UJzSO3aahd+HhHXop01/+qN9TicqMo7XmbozO1IUFlsGiPQlBh1hKY+qUmR83/Jy9F3tO9QS28pycXdj3kTCahukGwfRx0BMDq0oTad3gcaA99PVbthfpzZeq40VrYJgg==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-valkey-cluster-credentials
      namespace: harbor
    type: Opaque
