---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-minio-root-user
  namespace: harbor
spec:
  encryptedData:
    root-password: AgAnHuVS6yclmtedCLpBS74YL2vb+Vp1qSfzm2uFLLD5G+PNpHf4qEgpn/e9tRrJ7fYyq+IbvVAX+qyANafvsZD3Ej2T56IkRGjCq0YM/aDbbg6UOKNdMUPTaKcAruALfuqs+DNbwG8qj9DOhOvgj+Xd8Pauve4idHeX/nJVOrI6ks4fQWUEzSrn0xclG5gb5qBtv/BbceUEEELHiybL6SPy1GUu4mSpEXfNC375r7ZBlBcPLiOtZMTh+VIvq13AvrKwaosTe3EHWWwsCF4vmqqhlBP7efCSMHDSpQtc1FMn1VRWtMG4re70zyuUMtBpTJ6vHiricj6QQcBZIF/pS94zZRfGod8TE8nWtEtUfcZsOf57j1EHXV7tOLikm51Ii4LYbEs/fst7IY20kc6CLOGU5m6NI/CDUlgSBLRpXMNnArrk8Nzbu5Roh0Fw+toNrBFO4ZhrTq90PMlx2MQMgwFsUhK+qD6UE+93qZqC0EKadC1h24pONfj3EF88ymywtA2ezxJYTefG2F8juZuHaM2GDyzSwSU76beTjoo8+tSKhQhsTk7To+84JtnHJbLDBsDhaiUM8xKx5JsPW4vCQdFXmKGgMaImaLsDz9Dyfh8RchvLk0LEyrhrA75VG6yQ/b/P3ZxmdhofzxXJ/Lll6r7JDGqPhJzJhmm0BFxP9GfX/h8Cujn07ZrYqqTZHeK22/AVIqKgnVnmw8Dxw/EJKSp5f9bM/g==
    root-user: AgAQ92TDyyHw6d4zQqLON0aQS/zQazHcFj/XKiOx81SEZqs4COYcgfgDFjiRUV7nlFfRNnfNZuBglZFBUJUvIRaSYhvY9Y5n04Vw/UGR2Wcf3bHoskXKwLDWX0H+rdj6MmY7A1JA8PRVqXLqj6leMexqNOKxbFTq+ABnFZ+brKpLmGJSMolFBxpR1IWuNsnef0m/wvyuhUm4+y7gZgNLqHbyNc5d49xO4ip7KIMeoogN2HilO+cFLWv884++gnIQTUWyXN/H15AmlnkEPh0DH4JOdAgaDwZuY+HEWmdlqHn+KwcFHeDx1UxhfzFzd555N1R49T6VebiepiopUCkvPqtofW+wSpicbE6xIfNAFCOOH4N2fnwb4twQympDj7NYqm8kcyDbw5Q3v1O4S7yoL+fRf6UZLRfWNxuyLl2eSZUHlOlE/oSmEv2op8l44hTdiUAHd75rCj0YjgVh/t8SbMQlfrCmQdfqQ1TBq3/qiXwOJUMthPMUds0k4cJE95gMgwS2SKznCkzSVTIDxx81NVsnsyv2TXU3lbEW8LLhXx5lrr0I3qK/GcS5gGzxDdFVBL90RTWJgdPbs3tXg3NhOn5Sq83lgU4gBMO/ua9nBANr0530eANBAfIfw+4YzyGpm/BThnISbnAZkVLSdcwRBL5QruS4/G8uLaUWPAnDYYPku7/9dn6/paVH0tL4QvMO57hFxVcP8IQ=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-minio-root-user
      namespace: harbor
    type: Opaque
