expose:
  ingress:
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "dns01-cloudflare-cluster-issuer-prod"
    hosts:
      core: "harb.nailforge.dev"
  tls:
    certSource: "secret"
    secret:
      secretname: "harbor-tls"

persistence:
  persistentVolumeClaim:
    registry:
      storageClass: "synology-iscsi-retain"
    jobservice:
      jobLog:
        storageClass: "synology-iscsi-retain"
    database:
      storageClass: "synology-iscsi-retain"
    redis:
      storageClass: "synology-iscsi-retain"
    trivy:
      storageClass: "synology-iscsi-retain"