---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin
  namespace: gitea
spec:
  encryptedData:
    password: AgCckLG2Pvz9QpaEdw+mLnsIqLBpgM/jhQHLcb+HJ8JzBwh1fvJpKg7Qgt+uFLWI2B9B6MFQ2IL4yX5w9EqNc0ybxkAuVIOx4hTOCSljLLBpR0hPycet5g1tIpBfNvMN8Wn00/MPWgCrMXY6fRgAWasjro1nW3DqNPbYaYF0+6b9gSe73I7Y97/3zraJP3H5R4Yfh1irdfR19ah2iJtTDsENy54pAGob4Tkn1Tphv4+6fdYI612tvFCXaw35woskWBKQbvcKSEJOPqedr1ULMzQdl3xuhtMFbtjmPo1zoYt8F0vOwPbRtxVf/rCMrUJ/rtFqCfoh+Q60u3XEon9psWR3WTeIYr6vznjpysNKfVEdhX8bF7v4BxkRlu5LT6Y6ewShqMaBtTP7IC+FgCowohZrq/Ejc2HMkXhwGcNMtiBa9nqjfkwUolK7YGVsig/StIrBD0uLAjuNpZaN/caAHTsCMnYnh6B4qXvgZU/3tEssZxk+az9L24yKtn7bE9R2uvhwZY3XogMWraKVGoL0Lrjmnp8Xg5wwkbo0guydOzX97uAZlIUeQnDB7XgxXpW0UfwmsRBa770QLqpHlwhAzL1bPNaLg2pVHWETarwVuh4vMhlIhvnqLRw/DH9gBAlB9lLdpN+SDRBgp2TZjZM48hscptk1/ID/nz2WCXTtXC+LltvcD8r8UCh9A60zJ91Is985WaKPe/1jszb+HoFj0QnV/b/VtQ==
    username: AgAr5GnCURz3TZO/1OmZ9Sf0kgZ70GNDGbu0Hb+ENRmiHFlbZmsm/LagUZ+mExyF0ifKTo9i6FjHl+SgWRkqYglQyP4LCHc0JWrENjjwkW3qyfprHW708DyzZO9mGt3R6biEYJTNdAnZeZ5/pvX9iwa/HMRiE9pvngrQ37x3lM5T286kGsHB36df+OaxVYbhIm0j6vtLLZtUXWgHczywzGa8ke8IcvUgdTc1WI6m9TgpVxCPPcBW8726bW0YymkDDDzpTTZZWiFcJzgXs6PAkBC8OkQhj7TfDh9BYDBuRyC61dYOzAEAAXVZGSf+OzYKmzqRH8clUuhNjmF1tAy2l9HXVTRhMqzETxzv/Z1ihVT5tGOXoQ/0BNRgvVJYzowKtOHIihHbFT/OEuPYWka3Opb/sTM1VLyA9zXYFaloD/u81fN2fzqVkwFsa40iuGzslQTolX8SHt3x2BCItuHs/nwoznIBRdEDOrP3k4Qe9XNYC0Ez4X8lmr6kIYyxCa5pqFVRGVd05f5442tCsjcSZiIc2JrPtCysZJd6aWnfQQXXLdjeEyByvrBcRT+qK7fgn803xEd1B6QTzoRokjItJ911MLyyqSd+rFMiKPPVHNN1nafFBDObLiLZiPiRiIzmn5PvUMz79m5G40WDM8nEFASLuowRhcD99xuXOEJUy6NZBOBEd+zrng23tAGzg8YqpxYMQmAxipagYSz4bOo=
  template:
    metadata:
      creationTimestamp: null
      name: gitea-admin
      namespace: gitea
    type: Opaque
