---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-db-credentials
  namespace: gitea
spec:
  encryptedData:
    password: AgAS2JcCdxCdnYUa+hP2Gevjr2V5OnvziZXXA84NQA6wSSaUCekK+Y4e+HXukBJ5ISWOIArrnat18nn7X72lIsDMQDhu6KQE2Fm76LEOyo1YnIzzI3SkbAF9eBqqD9QtCKYLQ1iZuUf4YfOUHYWjfYadcNA9BGyLKt/xsYMr1h6Jv0wh71FMe30vqLd7bqCiX7Gyg/kd+IgNXceTZfis/05rYYRxh/oKqze0jhdooOzSyNXgJv5GarB8R+Lds+ihSrBAA5FHXV4HW4bqT8+NQ3zRMdlTHl5G8s98DYP2ZAn0Q82yr87F0bG+bQiBq6qiGq1IJ7TdYawY4FoON3hHXJDXJeQTdBdAsrIIX16dyvktoWxB1l2/lWP0xa1yOmgHzT+tFD+DhVr8xEjKps5Z1wXtUIUddPowm84DfFtvtJDYMeVvu3qxGxxQx3+1Ng/J/P41A6QQGCPelV2iVEfuh17qL0y6UZsTvAftCTWCOL/CaXiZrVxhQ2LpMgxJ3ddAwN8aMjopXXnfseyWpL90+IhIPrsNDP5t27Drw87E3jb5FTMt2wrWX6Rb+8ORvc7trSoWNy3B9LVHdJc7XiaXfFPb6tQFx36j0XKFsMQbKkPqlU9DKpdIDgniWFxydcYg2axRNE+8bvcErcSRKvm2IRHVLf+zqzxg8tZJ2YrO90CIcs9hTp5wzQ6V/D78z18XIegrBxBUzL7eDWCTjYSnb43hygeS0A==
    username: AgBrwYvRjQKDx26+YUIkn2cxF9o5NI1rVuTFitrulZF50BIFSz/5PW/D213v1vVOa8NY/AV01yFXm4Qsk6tpimJYLrFfB+XPKqbUDyF2Io47obRlOwZo5GZKY76T8+OD5ajux80F9IyYoPgIgXAr+MFnaH2jfkM8qFY/gVSvGongARhyweSA91Pjdbue3+ftrvrg3FPoXN42Ar9/YH+Q4v9EZJ9AuhEE3oiMReRJVWeVtYBJ0VZyhQsXg8pw9x8oetN4bYkHy5M1wdVFUXY192n2GTr1CxPH0T70pS9mqOMX6Lcz+iyZOyaln36gY8pgPc5H3mhGuFsE8H+qs9sEofYUOPrD5Phod52GBBRrDxigowloFREq0MuiSNzSI+mSH6Ykq8AyyWu0ix6SdZft2xkAl5Z9G5M2+MVbUnmgxtGmAbiwGjdjvWvY7YN+eqgbyBp67IMjmoG6euGztDGRnOn3qt9A5QYxjReC9949wtdGPyUH6Q2Wa+iBVB4c6kl/YPCc0UGBrWmwp+smi23vgp9/CVO6czLtPXRr8pZxsfZFH42bAUNW+TW7/44MAVT5lkYg6w8eX/Nqv8dP6gnDlxpgTFXytKpug0PzETscGPxvQV7VjxGVh0bIR2yjVJvFDmhokdKilnbV0Ah9gp/ViDCAzZQWN0U8VQbcnyJuVD9GF3AxSYaWjBx9Ot9liqPmblV7+/bOqw==
  template:
    metadata:
      creationTimestamp: null
      name: gitea-db-credentials
      namespace: gitea
    type: Opaque
