---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-loki-user
  namespace: minio
spec:
  encryptedData:
    loki-user: AgCQUVNkMCCz5jOV2pon1NnNX6uEdmJo7aG+U688CV3R0UAy476zsFQ6JzL9ekE0ug4NJ1dAlXsUMa2CMUdyncd8c0McqbqleWToU9fAhWUSfLgibM2EegHuu2d/SL25o9vA6svArn9jZbkvheIJdpWJfEPOd+8L6HpX7bJ0i8O2pE6+QidNvaKgcs6St24ohrOkqZmPNjFDui/DoFEg70806tLHSY3E08gCwgOcnp01BMQiZbRUswRi/X29p71pgfukrNIsx+fLk/NsHxyozeB9xcuWiCkJYBuZEZwWheTCcWTnd7RgSKUtuOOkbnB0f1w5AHO1QV9oVvgTKPIbRydpUKsZLiGw3h/iKhj1KOGo7I89dtKhKsKcWXSlITHjNd7MuBrj+v66F03lUMlLDkjLY45nNAVvRxBaqji0vW52XuMT1t0W27pAcDxWuhQpt38ICFj2mL34S8txUOKMd+Irv0Pb/eQRRQAgdC0P54a4Z3yc7MdQD5qhXtfUjaU+4rDnKu5nTmhytOHPKsjr73YIOb4e5AcE1Y3W83RPJbldebAgrUe3YtTgGAZg/byqP8ovE3ZYgCWHpJJcrKC4E7BPnH8+hCn/ZCfO8Eab5VpZOyfQGxDbnirY4V0wsZi0vzwxuHj7G6uYpqfxVV9WGazV8NNus6b+XmPl2b/eCxNf+RxvR/kBtNFWy/dQ/GMBmXXm/R69fy4XaiSuJ0HdcvxcF28SO2h16HtmtpU7p2MxTAwgelpaaER/IsGWuugV/pj7sgMX9o77yngJGZBIo1an9JMXa85lRVvqPEn2txFEKlSuLGR3SUz4HuiJOCuM4A5cBvOHXMU1PT0krw==
  template:
    metadata:
      creationTimestamp: null
      name: minio-loki-user
      namespace: minio
    type: Opaque
